### ISSUE TITLE
PFRTester and project_freeride directory question

### ISSUE THREAD

**Issue by ericblade** [GENIVI/genivi-vehicle-simulator#4]
Are these directories used in the main project somehow or other that I'm not seeing?

According to the Unity manual, only Assets and ProjectSettings directories should be under version control . . . and I'm trying to do some moving around of things, but then Unity starts complaining about the PFRTester and project_freeride directories having Library folders that they shouldn't have.  

Would those directories (as well as the input plugin, and Tools) be better suited as separate repositories from the main?

**Comment by DanielSchambach** [comment]
@ericblade - sorry PFRTester & project_freeride were from previous projects and henceforth have been removed.

**Comment by DanielSchambach** [comment]
@ericblade - methinks some of these are legacy directories
