### ISSUE TITLE
Simulator software using lots of bandwidth

### ISSUE THREAD

**Issue by jeremiah** [GENIVI/genivi-vehicle-simulator#5]
Hi!

Firstly, thanks for all your work on this project. :-) It is getting a fair amount of downloads from GitHub according to GitHub's own metrics on the bandwidth that we purchased. In fact, we ran out of bandwidth last week and are purchasing more from GitHub. This leads us to ask if there is not a better location, something more affordable perhaps, that we might move downloads of the built software to? From what I can tell there haven't been many commits in January and that makes me believe that much of the traffic is just downloading the files by users. Perhaps there is a better place for that type of distribution than GitHub?

**Comment by DanielSchambach** [comment]
HI Jeremiah, 
Happy to discuss options. We could possibly move it over to Elements' GitLab repo & just link from Genivi's site to the new repo. J, do you want to chat with Steve about this? (unsure if there are other ramifications we aren't aware of. Let me know if you'd like to discuss. thanks

**Comment by jeremiah** [comment]
Super! This is not a huge issue, just something that GENIVI folks are wondering about. Moving it to Element's GitLab repo might be a good alternative. GENIVI also hosts large file for download on docs.genivi.org which might be another option. Though getting the files there might be more of a hassle. I suspect there is some automated tooling with the Elements' GitLab which likely makes publishing easier, am I right in that assumption?

**Comment by ericblade** [comment]
The group I'm working with may have caused a large spike in that, while checking the software out, setting up auto builders, distributing to the team members and such.  We should all be operating on forks out here, or internal repos now, though. not sure if forks are counted on those metrics.

**Comment by jeremiah** [comment]
Thanks Eric. If that is the case then perhaps February will be lower bandwidth month and we won't need additional bandwith.

**Comment by DanielSchambach** [comment]
@jeremiah - we'll wait to hear from you with February's stats. thanks

**Comment by ericblade** [comment]
FWIW, since this message, I turned off an auto-builder that was paying attention to my fork, and I'm pretty sure that we're all cloning from an internal mirror now.
