### ISSUE TITLE
Empty in the folder I download

### ISSUE THREAD

**Issue by wallacewangchao** [GENIVI/genivi-vehicle-simulator#8]
Dear Guys,

I am a PhD candidate in Eindhoven University of Technology, the Netherlands. I am really interested in your open source Simulator as my research is about HCI of driving. 

However, after I download the simulator source code and open any scenes it in Unity, there is no object inside. After extracted, the size of the folder is 621,3 MB. And each scene file is only several K. But the files in the Github online are much bigger. 

see pics:
https://chaoswang.files.wordpress.com/2017/04/screen-shot-2017-04-26-at-11-04-42.png
https://chaoswang.files.wordpress.com/2017/04/screen-shot-2017-04-26-at-11-05-46.png
https://chaoswang.files.wordpress.com/2017/04/screen-shot-2017-04-26-at-11-16-45.png

I have no idea what is wrong with the file, I have tried several times in different PC and Mac, using GitHub desktop application or not. But they all did not work.

Could you please provide a complete version of this software? 
Thanks a lot

**Comment by heeen** [comment]
you need to install git-lfs and checkout again

**Comment by heeen** [comment]
git-lfs is a way to only store hashes for big files in the actual git repo, while the big files are on some other file server.

it can be a little tricky to get it working right, I will suggest to install it and do a fresh clone

**Comment by wallacewangchao** [comment]
Thanks a lot for you help! It works. but I have some question about the networking, which will be in another issue
